- family_name: 清澄
  family_name_ruby: きよすみ
  personal_name: アキラ
- family_name:
  family_name_ruby:
  personal_name: ニコ
- family_name: 御稜
  family_name_ruby: ごりょう
  personal_name: ナグサ
- family_name:
  family_name_ruby:
  personal_name: プラナ
- family_name: 扇喜
  family_name_ruby: おき
  personal_name: アオイ
- family_name: 岩櫃
  family_name_ruby: いわびつ
  personal_name: アユム
- family_name:
  family_name_ruby:
  personal_name: イブキ
- family_name:
  family_name_ruby:
  personal_name: ウミカ
- family_name:
  family_name_ruby:
  personal_name: オトギ
- family_name: 申谷
  family_name_ruby: しんたに
  personal_name: カイ
- family_name: 不知火
  family_name_ruby: しらぬい
  personal_name: カヤ
- family_name: 竜華
  family_name_ruby: りゅうげ
  personal_name: キサキ
- family_name:
  family_name_ruby:
  personal_name: クズノハ
- family_name:
  family_name_ruby:
  personal_name: クルミ
- family_name:
  family_name_ruby:
  personal_name: サツキ
- family_name: 川流
  family_name_ruby: かわる
  personal_name: シノン
- family_name:
  family_name_ruby:
  personal_name: ジェネラル
- family_name:
  family_name_ruby:
  personal_name: スモモ
- family_name: 百合園
  family_name_ruby: ゆりぞの
  personal_name: セイア
- family_name:
  family_name_ruby:
  personal_name: ソラ
- family_name:
  family_name_ruby:
  personal_name: デカルト
- family_name: 天地
  family_name_ruby: あまち
  personal_name: ニヤ
- family_name:
  family_name_ruby:
  personal_name: ハイネ
- family_name:
  family_name_ruby:
  personal_name: バルバラ
- family_name:
  family_name_ruby:
  personal_name: フランシス
- family_name:
  family_name_ruby:
  personal_name: プレジデント
- family_name: 風巻
  family_name_ruby: かざまき
  personal_name: マイ
- family_name: 羽沼
  family_name_ruby: はぬま
  personal_name: マコト
- family_name: 姫木
  family_name_ruby: ひめき
  personal_name: メル
- family_name: 秋泉
  family_name_ruby: あきいずみ
  personal_name: モミジ
- family_name: 由良木
  family_name_ruby: ゆらき
  personal_name: モモカ
- family_name: 七度
  family_name_ruby: しちど
  personal_name: ユキノ
- family_name: 河駒風
  family_name_ruby: こまかぜ
  personal_name: ラブ
- family_name: 調月
  family_name_ruby: つかつき
  personal_name: リオ
- family_name: 七神
  family_name_ruby: なながみ
  personal_name: リン
- family_name: 鹿山
  family_name_ruby: かやま
  personal_name: レイジョ
- family_name: 旗見
  family_name_ruby: はたみ
  personal_name: エリカ
- family_name:
  family_name_ruby:
  personal_name: キララ
- family_name:
  family_name_ruby:
  personal_name: アロナ
- family_name: 三善
  family_name_ruby: みよし
  personal_name: タカネ
- family_name: 荒槇
  family_name_ruby: あらまき
  personal_name: ヤクモ
- family_name:
  family_name_ruby:
  personal_name: アラタ
- family_name: 桐生
  family_name_ruby: きりゅう
  personal_name: キキョウ
- family_name: 不破
  family_name_ruby: ふわ
  personal_name: レンゲ
- family_name:
  family_name_ruby:
  personal_name: コクリコ
- family_name:
  family_name_ruby:
  personal_name: シュロ
- family_name: ''
  family_name_ruby: ''
  personal_name: ユメ
- family_name: 元宮
  family_name_ruby: もとみや
  personal_name: チアキ
- family_name: 野正
  family_name_ruby: のまさ
  personal_name: レイ
- family_name: 橘
  family_name_ruby: たちばな
  personal_name: ヒカリ
- family_name: 橘
  family_name_ruby: たちばな
  personal_name: ノゾミ
- family_name: 朝霧
  family_name_ruby: あさぎり
  personal_name: スオウ
- family_name: 椎名
  family_name_ruby: しいな
  personal_name: ツムギ
