- family_name:
  family_name_ruby:
  personal_name: アキラ
- family_name:
  family_name_ruby:
  personal_name: ニコ
- family_name:
  family_name_ruby:
  personal_name: ナグサ
- family_name:
  family_name_ruby:
  personal_name: プラナ
- family_name:
  family_name_ruby:
  personal_name: アオイ
- family_name:
  family_name_ruby:
  personal_name: アユム
- family_name:
  family_name_ruby:
  personal_name: イチカ
- family_name:
  family_name_ruby:
  personal_name: イブキ
- family_name:
  family_name_ruby:
  personal_name: ウミカ
- family_name:
  family_name_ruby:
  personal_name: オトギ
- family_name:
  family_name_ruby:
  personal_name: カイ
- family_name:
  family_name_ruby:
  personal_name: カスミ
- family_name:
  family_name_ruby:
  personal_name: カヤ
- family_name:
  family_name_ruby:
  personal_name: キサキ
- family_name:
  family_name_ruby:
  personal_name: クズノハ
- family_name:
  family_name_ruby:
  personal_name: クルミ
- family_name:
  family_name_ruby:
  personal_name: ゴルコンダ
- family_name:
  family_name_ruby:
  personal_name: サツキ
- family_name:
  family_name_ruby:
  personal_name: シノン
- family_name:
  family_name_ruby:
  personal_name: ジェネラル
- family_name:
  family_name_ruby:
  personal_name: スモモ
- family_name:
  family_name_ruby:
  personal_name: セイア
- family_name:
  family_name_ruby:
  personal_name: ソラ
- family_name:
  family_name_ruby:
  personal_name: デカルト
- family_name:
  family_name_ruby:
  personal_name: ニヤ
- family_name:
  family_name_ruby:
  personal_name: ハイネ
- family_name:
  family_name_ruby:
  personal_name: バルバラ
- family_name:
  family_name_ruby:
  personal_name: フランシス
- family_name:
  family_name_ruby:
  personal_name: プレジデント
- family_name:
  family_name_ruby:
  personal_name: マイ
- family_name:
  family_name_ruby:
  personal_name: マエストロ
- family_name:
  family_name_ruby:
  personal_name: マコト
- family_name:
  family_name_ruby:
  personal_name: メル
- family_name:
  family_name_ruby:
  personal_name: モミジ
- family_name:
  family_name_ruby:
  personal_name: モモカ
- family_name:
  family_name_ruby:
  personal_name: ユキノ
- family_name:
  family_name_ruby:
  personal_name: ラブ
- family_name:
  family_name_ruby:
  personal_name: リオ
- family_name:
  family_name_ruby:
  personal_name: リン
- family_name:
  family_name_ruby:
  personal_name: レイジョ
- family_name:
  family_name_ruby:
  personal_name: エリカ
- family_name:
  family_name_ruby:
  personal_name: キララ
