- family_name: 清澄
  family_name_ruby: きよすみ
  personal_name: アキラ
- family_name:
  family_name_ruby:
  personal_name: ニコ
- family_name: 御稜
  family_name_ruby: ごりょう
  personal_name: ナグサ
- family_name:
  family_name_ruby:
  personal_name: プラナ
- family_name: 扇喜
  family_name_ruby: おき
  personal_name: アオイ
- family_name:
  family_name_ruby:
  personal_name: アユム
- family_name:
  family_name_ruby:
  personal_name: イチカ
- family_name:
  family_name_ruby:
  personal_name: イブキ
- family_name:
  family_name_ruby:
  personal_name: ウミカ
- family_name:
  family_name_ruby:
  personal_name: オトギ
- family_name: 申谷
  family_name_ruby: しんたに
  personal_name: カイ
- family_name:
  family_name_ruby:
  personal_name: カスミ
- family_name: 不知火
  family_name_ruby: しらぬい
  personal_name: カヤ
- family_name:
  family_name_ruby:
  personal_name: キサキ
- family_name:
  family_name_ruby:
  personal_name: クズノハ
- family_name:
  family_name_ruby:
  personal_name: クルミ
- family_name:
  family_name_ruby:
  personal_name: サツキ
- family_name: 川流
  family_name_ruby: かわる
  personal_name: シノン
- family_name:
  family_name_ruby:
  personal_name: ジェネラル
- family_name:
  family_name_ruby:
  personal_name: スモモ
- family_name:
  family_name_ruby:
  personal_name: セイア
- family_name:
  family_name_ruby:
  personal_name: ソラ
- family_name:
  family_name_ruby:
  personal_name: デカルト
- family_name:
  family_name_ruby:
  personal_name: ニヤ
- family_name:
  family_name_ruby:
  personal_name: ハイネ
- family_name:
  family_name_ruby:
  personal_name: バルバラ
- family_name:
  family_name_ruby:
  personal_name: フランシス
- family_name:
  family_name_ruby:
  personal_name: プレジデント
- family_name: 風巻
  family_name_ruby: かざまき
  personal_name: マイ
- family_name: 羽沼
  family_name_ruby: はぬま
  personal_name: マコト
- family_name: 姫木
  family_name_ruby: ひめき
  personal_name: メル
- family_name: 秋泉
  family_name_ruby: あきいずみ
  personal_name: モミジ
- family_name:
  family_name_ruby:
  personal_name: モモカ
- family_name: 七度
  family_name_ruby: しちど
  personal_name: ユキノ
- family_name:
  family_name_ruby:
  personal_name: ラブ
- family_name: 調月
  family_name_ruby: つかつき
  personal_name: リオ
- family_name:
  family_name_ruby:
  personal_name: リン
- family_name: 鹿山
  family_name_ruby: かやま
  personal_name: レイジョ
- family_name: 旗見
  family_name_ruby: はたみ
  personal_name: エリカ
- family_name:
  family_name_ruby:
  personal_name: キララ
- family_name:
  family_name_ruby:
  personal_name: アロナ
